### ISSUE TITLE
Special volume paths in Docker for Windows

### ISSUE THREAD

**Issue by agavrilov** [emk/compose_yml#22]
Docker for Windows allows to specify special paths in volumes sub-section of service section. These paths must NOT be converted to Windows equivalent. Examples:
```yaml
services:
    test:
        volumes:
            - /dev/shm:/dev/shm
            - /var/run/docker.sock:/var/run/docker.sock
            - "/sys:/sys:ro"
            - "/var/run:/var/run:rw"
```
